version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: camillia
      POSTGRES_DB: student_project_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=student_project_manager
      - DB_USER=postgres
      - DB_PASSWORD=camillia
      - JWT_SECRET=votre_secret_jwt_tres_securise
      - JWT_EXPIRES_IN=24h
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=seaconnectteam@gmail.com
      - EMAIL_PASSWORD=rrsfbhnqxludgdhk
      - EMAIL_FROM=seaconnectteam@gmail.com
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=uploads
      - FORCE_SYNC=false
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data:
