name: CI Docker Multi-Job

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l'image Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pa-back:latest .

      - name: Sauvegarder l'image comme artefact
        run: docker save ${{ secrets.DOCKERHUB_USERNAME }}/pa-back:latest -o image.tar

      - name: Upload de l'image buildée
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar

  push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Télécharger l'image
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push sur Docker Hub
        run: |
          docker load -i image.tar
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pa-back:latest